# Aliases
alias d="/Users/janolehuebner/dev/bin/mdl"
alias vim="nvim"
alias vi="nvim"
alias nano="nvim"
alias tg="terragrunt"
alias tf="tofu"
alias terraform="tofu"
alias pip="pip3"
alias python="python3"
alias cookies="open /Users/janolehuebner/Library/Containers/com.apple.Safari/Data/Library/Cookies/"
alias dotfiles="git --work-tree=$HOME --git-dir=$HOME/.dotgit "
